import { PrismaClient } from "@prisma/client";  // generated by prisma-client-js → node_modules/@prisma/client

/**
 * ---------------------------------------------------------
 *  TechHat Typing Master — Prisma Client Singleton
 * ---------------------------------------------------------
 *  Prisma 7: connection URL is passed via `datasourceUrl`
 *  in the constructor (schema.prisma no longer holds URLs).
 *
 *  The globalThis pattern prevents new instances on every
 *  Next.js hot-reload in development.
 *
 *  Usage: import { prisma } from "@/lib/prisma";
 * ---------------------------------------------------------
 */

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    // Prisma 7: database URL is resolved from prisma.config.ts / env vars
    log:
      process.env.NODE_ENV === "development"
        ? ["query", "error", "warn"]
        : ["error"],
  });

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
